/**
 * Build-artifact parity test for prompt .md artifacts (v0.7 Step
 * 2.3.a.0 — Path-γ Read-tool refactor substrate).
 *
 * Verifies that `dist/extraction/prompt.md` + `dist/generation/
 * prompt.md` (generated by `scripts/generate-prompt-artifacts.mjs`
 * after `tsc`) match the canonical `EXTRACTION_PROMPT` +
 * `GENERATE_ADRS_PROMPT` constants exported by the .ts source-of-
 * truth. Catches silent drift if the build script is bypassed or
 * the .md artifacts are hand-edited.
 *
 * Skips gracefully when `dist/` hasn't been built (test substrate
 * should not fail in environments that run only `npm test` without
 * `npm run build` first; the parity invariant is a build-time
 * guarantee, not a test-time prerequisite).
 */

import { describe, expect, it } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve as pathResolve } from "node:path";
import { fileURLToPath } from "node:url";

import { EXTRACTION_PROMPT } from "./prompt.js";
import { GENERATE_ADRS_PROMPT } from "../generation/prompt.js";

const here = dirname(fileURLToPath(import.meta.url));
// src/extraction/prompt-artifact-parity.test.ts → ../../dist/
const distRoot = pathResolve(here, "..", "..", "dist");

describe("prompt artifact parity (v0.7 Step 2.3.a.0)", () => {
  const extractionMdPath = pathResolve(distRoot, "extraction", "prompt.md");
  const generateAdrsMdPath = pathResolve(distRoot, "generation", "prompt.md");

  const distBuilt =
    existsSync(extractionMdPath) && existsSync(generateAdrsMdPath);

  it.skipIf(!distBuilt)(
    "dist/extraction/prompt.md matches EXTRACTION_PROMPT constant",
    () => {
      const artifact = readFileSync(extractionMdPath, "utf8");
      expect(artifact).toBe(EXTRACTION_PROMPT);
    },
  );

  it.skipIf(!distBuilt)(
    "dist/generation/prompt.md matches GENERATE_ADRS_PROMPT constant",
    () => {
      const artifact = readFileSync(generateAdrsMdPath, "utf8");
      expect(artifact).toBe(GENERATE_ADRS_PROMPT);
    },
  );

  if (!distBuilt) {
    it("dist/ artifacts not built (skipped parity checks); run `npm run build`", () => {
      // Surface as a passing informational test rather than silently
      // hiding the absence — keeps CI signal honest.
      expect(distBuilt).toBe(false);
    });
  }
});
