/**
 * Config scaffold writer for `contextatlas init` per v0.6 Step 4.2
 * (Stream A pipeline assembly per Q4.0.5 lock + Q4.2.1-Q4.2.5 sub-
 * adjudications). Writes initial `.contextatlas.yml` at repo root
 * preserving existing config per Q4.0.12 idempotent skip-when-present
 * lock.
 *
 * Pure-function `buildConfigScaffold` produces YAML string; idempotent
 * `writeConfigScaffold` checks existence before writing. Q4.2.4 lock:
 * languages list passed in by caller — Step 4.2 hard-codes
 * ["typescript"] placeholder; Step 4.3 wires H5 detection per Q11-
 * style refinement.
 */

import { existsSync, writeFileSync } from "node:fs";
import { resolve as pathResolve } from "node:path";

import yaml from "js-yaml";

import { DEFAULT_CONFIG_FILENAME } from "../config/defaults.js";
import type { LanguageCode } from "../types.js";

export type ConfigScaffoldResult =
  | { readonly status: "created"; readonly path: string }
  | { readonly status: "preserved"; readonly path: string };

export interface ConfigScaffoldOptions {
  readonly configRoot: string;
  readonly architecture: "anthropic-api-claude-code" | "claude-code-only";
  readonly languages: readonly LanguageCode[];
  /**
   * When true, write `observability: { enabled: true }` into the
   * scaffold per v0.6 Step 6.2 / Q6.0.4 hybrid wiring. The flag IS
   * the consent signal per ADR-20 cohort observability contract.
   * Default false (section absent → observability disabled).
   */
  readonly observe?: boolean;
}

/**
 * Build YAML scaffold string. Pure function (no I/O); inputs come
 * from runner per Q4.2.4 lock.
 *
 * Header comment surfaces provenance ("generated by `contextatlas
 * init`") + DESIGN.md cross-reference per Point 4 lock at Step 4.2
 * surface review (cohort UX provenance + schema documentation
 * pointer).
 */
export function buildConfigScaffold(opts: {
  readonly architecture: "anthropic-api-claude-code" | "claude-code-only";
  readonly languages: readonly LanguageCode[];
  readonly observe?: boolean;
}): string {
  const header =
    "# ContextAtlas configuration (generated by `contextatlas init`).\n" +
    "# See DESIGN.md for full schema; ADR-08 for runtime invariants.\n";
  const config: Record<string, unknown> = {
    version: 1,
    architecture: opts.architecture,
    languages: [...opts.languages],
    adrs: {
      path: "docs/adr/",
      format: "markdown-frontmatter",
    },
    docs: {
      include: ["README.md", "DESIGN.md", "docs/**/*.md"],
    },
    atlas: {
      committed: true,
      path: ".contextatlas/atlas.json",
      local_cache: ".contextatlas/index.db",
    },
  };
  if (opts.observe === true) {
    // Per ADR-20 cohort observability contract: --observe IS the
    // consent signal; section emitted only when explicitly requested.
    config.observability = { enabled: true };
  }
  return header + yaml.dump(config, { lineWidth: 100, noRefs: true });
}

/**
 * Write scaffold to repo root, preserving existing config per Q4.0.12
 * idempotent skip-when-present lock. Returns result enum describing
 * what happened.
 */
export function writeConfigScaffold(
  opts: ConfigScaffoldOptions,
): ConfigScaffoldResult {
  const path = pathResolve(opts.configRoot, DEFAULT_CONFIG_FILENAME);
  if (existsSync(path)) {
    return { status: "preserved", path };
  }
  const yamlContent = buildConfigScaffold({
    architecture: opts.architecture,
    languages: opts.languages,
    observe: opts.observe,
  });
  writeFileSync(path, yamlContent, "utf8");
  return { status: "created", path };
}
