import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import { loadConfig } from "../config/parser.js";
import {
  buildConfigScaffold,
  writeConfigScaffold,
} from "./config-scaffold.js";

describe("buildConfigScaffold (pure function)", () => {
  it("includes architecture: anthropic-api-claude-code in YAML output", () => {
    const yamlOut = buildConfigScaffold({
      architecture: "anthropic-api-claude-code",
      languages: ["typescript"],
    });
    expect(yamlOut).toContain("architecture: anthropic-api-claude-code");
    expect(yamlOut).toContain("- typescript");
  });

  it("includes architecture: claude-code-only when ccOnly path", () => {
    const yamlOut = buildConfigScaffold({
      architecture: "claude-code-only",
      languages: ["typescript"],
    });
    expect(yamlOut).toContain("architecture: claude-code-only");
  });

  it("includes provenance + DESIGN.md cross-reference header (Point 4 lock)", () => {
    const yamlOut = buildConfigScaffold({
      architecture: "anthropic-api-claude-code",
      languages: ["typescript"],
    });
    expect(yamlOut).toContain(
      "# ContextAtlas configuration (generated by `contextatlas init`)",
    );
    expect(yamlOut).toContain("# See DESIGN.md for full schema");
  });

  it("output round-trips through loadConfig (parser accepts scaffold)", async () => {
    const tmpRoot = await mkdtemp(
      path.join(tmpdir(), "scaffold-roundtrip-"),
    );
    try {
      const yamlOut = buildConfigScaffold({
        architecture: "claude-code-only",
        languages: ["typescript"],
      });
      const cfgPath = path.join(tmpRoot, ".contextatlas.yml");
      await writeFile(cfgPath, yamlOut, "utf8");

      const cfg = loadConfig(tmpRoot);
      expect(cfg.architecture).toBe("claude-code-only");
      expect(cfg.languages).toEqual(["typescript"]);
      expect(cfg.adrs.path).toBe("docs/adr");
      expect(cfg.atlas.committed).toBe(true);
    } finally {
      await rm(tmpRoot, { recursive: true, force: true });
    }
  });
});

describe("writeConfigScaffold (idempotent writer)", () => {
  let tmpRoot: string;

  beforeEach(async () => {
    tmpRoot = await mkdtemp(path.join(tmpdir(), "scaffold-write-"));
  });

  afterEach(async () => {
    await rm(tmpRoot, { recursive: true, force: true });
  });

  it("creates .contextatlas.yml at repo root when absent (status: 'created')", async () => {
    const result = writeConfigScaffold({
      configRoot: tmpRoot,
      architecture: "anthropic-api-claude-code",
      languages: ["typescript"],
    });
    expect(result.status).toBe("created");
    expect(result.path).toBe(path.resolve(tmpRoot, ".contextatlas.yml"));

    const written = await readFile(result.path, "utf8");
    expect(written).toContain("architecture: anthropic-api-claude-code");
  });

  it("preserves existing .contextatlas.yml when present (status: 'preserved')", async () => {
    const existingPath = path.join(tmpRoot, ".contextatlas.yml");
    const existingContent = "version: 1\narchitecture: claude-code-only\n";
    await writeFile(existingPath, existingContent, "utf8");

    const result = writeConfigScaffold({
      configRoot: tmpRoot,
      architecture: "anthropic-api-claude-code",
      languages: ["typescript"],
    });
    expect(result.status).toBe("preserved");
    expect(result.path).toBe(path.resolve(tmpRoot, ".contextatlas.yml"));

    const onDisk = await readFile(result.path, "utf8");
    expect(onDisk).toBe(existingContent);
  });
});

describe("buildConfigScaffold — observability section (v0.6 Step 6.2)", () => {
  it("omits observability section when observe is absent (default off)", () => {
    const yamlOut = buildConfigScaffold({
      architecture: "anthropic-api-claude-code",
      languages: ["typescript"],
    });
    expect(yamlOut).not.toContain("observability");
  });

  it("omits observability section when observe is false", () => {
    const yamlOut = buildConfigScaffold({
      architecture: "anthropic-api-claude-code",
      languages: ["typescript"],
      observe: false,
    });
    expect(yamlOut).not.toContain("observability");
  });

  it("emits observability.enabled: true when observe is true", () => {
    const yamlOut = buildConfigScaffold({
      architecture: "anthropic-api-claude-code",
      languages: ["typescript"],
      observe: true,
    });
    expect(yamlOut).toContain("observability:");
    expect(yamlOut).toContain("enabled: true");
  });

  it("observe-true scaffold round-trips through loadConfig", async () => {
    const tmpRoot = await mkdtemp(
      path.join(tmpdir(), "scaffold-observe-roundtrip-"),
    );
    try {
      const yamlOut = buildConfigScaffold({
        architecture: "anthropic-api-claude-code",
        languages: ["typescript"],
        observe: true,
      });
      const cfgPath = path.join(tmpRoot, ".contextatlas.yml");
      await writeFile(cfgPath, yamlOut, "utf8");

      const cfg = loadConfig(tmpRoot);
      expect(cfg.observability).toEqual({ enabled: true });
    } finally {
      await rm(tmpRoot, { recursive: true, force: true });
    }
  });
});
